name: Simplify STEP File

on:
  push:
    paths:
      - '*.step'

jobs:
  simplify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install CadQuery
        run: |
          pip install cadquery

      - name: Run Simplifier
        run: |
          python simplify_step.py

      - name: Commit simplified STEP
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add .
          git commit -m 'Add simplified STEP file'
          git push
